- name: "create a ~/web directory"
  file:
    path: ~/web
    state: directory

- name: "copy the zipped artifact into the server"
  become: true
  become_method: sudo
  template:
    src: "~/project/artifact.tar.gz"
    dest: "~/artifact.tar.gz"

- name: Extract artifact.tar.gz into ~/web
  ansible.builtin.unarchive:
    src: ~/artifact.tar.gz
    dest: ~/web
    remote_src: yes

- name: "Start server"
  become: true
  become_method: sudo
  raw: |
    cd ~/web
    npm install
    pm2 stop default
    pm2 start npm -- start
    