- name: "create a ~/web directory"
  become: true
  become_method: sudo
  file:
    path: ~/backend
    state: directory

- name: "copy the zipped artifact into the server"
  become: true
  become_method: sudo
  copy:
    src: "artifact.tar.gz"
    dest: "~/artifact.tar.gz"
    mode: "0777"
    backup: yes

- name: Extract artifact.tar.gz into ~/web
  become: true
  become_method: sudo
  ansible.builtin.unarchive:
    src: ~/artifact.tar.gz
    dest: ~/backend
    remote_src: yes

- name: "Executing Node app with PM2"
  become: true
  become_method: sudo
  shell: |
    cd ~/backend
    npm install
    pm2 stop default
    pm2 start npm -- start -f
    pm2 list
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  become: true
  become_method: sudo
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save
